spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TomatoMall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8080

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: 

alipay:
  appId: 2021000147699869
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCvHDZ3Zup9sna5P7kH2Wm1UnqFGSaVGOEmb/Li0cb1E8LErZcN1Co1BV2i3RFQ+ZA/un4XnV29Zz77FbYanzxa4lMKnYIdME6sajxkNTwesCKWUSfaMqE84QkYJkVOtWah7Gc9Z/5ZxH5AFduzW5Pe0Eyd+UBUPKffRT/zX2XFwJhMsEGtUTdvacnsiugj63P/h6FQwPS3iaLVdEFY1teYfXXZ31tYFfDO8Udq9DFojSnNaK/I4M6kZZP9UP+RdyfHeGkvbiEqGibQXlkzYqMnz6dmrjYRSskqPqcBP1aWTjpUc3OfvBJhDs4tnOUzBpLJSps2opARRXgt/Hwtpwv/AgMBAAECggEAUAjzFAvj7WOeQ/lOFrpWSFvUR/VA3zCp56mPOABtkSJhCQfWXKm2SNmU/JVSDtKiDZ6tdxmj+Kex74zy2KQjL9712Yo4KCMmMkO0KpDyU4xpoo6hSmeNroekYndLgjgDGss0PKrFZD4c/il/azDWGybVffaoYlf+2luKaTAXEhS6iMrkTyRKLlETzqFcDQPB3cF/3YhygzIbc/8lXYip99Ejy69sb7lNUSYqiZ2PtCCIU+y/3vHtB9V8koVNoxlbSimeSu6UKl6IktK3bIVgg7c4Ov7qTns4les0ZP0uIzY/9iV9rQMkPOpZprAWtviGWNeQJ2ZW0EFRNY0jgyjvMQKBgQD8EM5J0VDX7usPh3pDrIRwERv1PqmzqPjYucfcNIrtzatkRxVUL4kg2H8s50KQqkMKJNUZW2Py/QIQg1uBU7BugAVsKDPjr+Ic7Ow0t7UA/hNccDNhI6Gapq9Aa5rhnymhstpTj/EQRSUdSTJaBx+x+gwz9L4VSmUXDuUBQjDsCwKBgQCx1+lPCGL0FcphTyi4cd2vBKExdGOorU1EX1+IrAxDfdeGSyjbstEJyLWoRHvKib54kl0Y5nSrtdyqFtJDa9mkaa2ucpSVbeOTHZW17tN8Pd+J7l41B5hEiXEgZkgcjsVCXDBL0K3arN9crxJQuM4QrM1pMp/VMW6uoVYiMCdkXQKBgFnXp59Z8uW0K6YyVJrQX7gN8RgdiKEXpfKhbSIIvEf8WY15ZJnIA6loYRPhLbGgbhqsfCP4lgxir5yxJSlYafdIvCYLwkryQraqn5o+rE45QS9ecoG6EHyt0qM0d1TZxR30QKsuD+8LpinlEARUq7Bk/np6TlIKXTO1xFwJeqR3AoGAUzol91SHao8gDPYMqnSvOA7EmO5NDU09EbhIbx+FBbjIuhJGZrqCVT/Ws46JGDnqJ2bnppWDGDCdugPAFslMK0NBgpggrOWmUNzRiTjhRA14pYYmFE8flUN066KyMJsn+WxHNdPM6L9qMGfF/HzgArG713VXk1/02kiqlIlQhgkCgYEA8MpaHcr+TWO1iwKppja9GrWcoQiAThdanvgaBBjWltwMYrfRK1rXT8eNgtQfHeUNy2oCBRDniWT7yAKg4IDM47tSGUyFByhm+JiFCDKvl4nsqsnBOAIYvMUE+dkDQX3/1ZjzN3e95I7b6mWZmFD9VvKFDzjRs1qiCt2xCNIUnH0=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgw5ne8DcVvSoegeDjwcru/LghpvQEm648yHQwG8Uz6cSALqtvvQHAJIBdmyUCiG6d6SEOpJ8oarfO8QhmXEc6X6yTxIQeP6zrFlYAbXpAWV7lT35y/5IsMifkoOnreSGobgKY0S8AuWRHjUjeGbr65PxvqVmzZ5Ss26GxjHOaA4+LdTzlE3uaIIWh9imfXQeqxTcKNzmbkC2TVv3oYFXDcdFddwx2VooPx+XaBvyvSUCPFRyc5mf5B/0HNOix+sR5RpLkMJIfpyQWZXRT/NtmC8xSEpSdJfjODsMSa2R04ZtxrvSOxyay7b5BKa808Gt4YCu0zOobU0ZKNXUgPjIhwIDAQAB
  notifyUrl: http://vkqd3u.natappfree.cc/alipay/notify
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  returnUrl:  http://vkqd3u.natappfree.cc/alipay/returnUrl
  charset: utf-8
  signType: RSA2

